#! /Users/tomi/Library/Perl58/bin/perl

use strict;
use Cwd;
use File::Spec;

BEGIN {
  $^W = 1;  # Use warnings
  my $curdir = File::Spec->canonpath( Cwd::cwd() );
  unless ($curdir eq '/Users/tomi/svn/Projects/Text-Textile') {
    die ('This script must be run from /Users/tomi/svn/Projects/Text-Textile, not '."$curdir\n".
	 "Please re-run the Build.PL script here.\n");
  }
  @INC = 
    (
     '/sw/lib/perl5',
     '/sw/lib/perl5/darwin',
     '/Users/tomi/Library/Perl58/lib/perl5/5.8.5/darwin-thread-multi-2level',
     '/Users/tomi/Library/Perl58/lib/perl5/5.8.5',
     '/Users/tomi/Library/Perl58/lib/perl5/site_perl/5.8.5/darwin-thread-multi-2level',
     '/Users/tomi/Library/Perl58/lib/perl5/site_perl/5.8.5',
     '/Users/tomi/Library/Perl58/lib/perl5/site_perl',
     '/Users/tomi/svn/Projects/Text-Textile'
    );
}

use Module::Build;

if (-e 'Build.PL' and not Module::Build->up_to_date("Build.PL", $0)) {
   warn "Warning: Build.PL has been altered.  You may need to run 'perl Build.PL' again.\n";
}

# This should have just enough arguments to be able to bootstrap the rest.
my $build = Module::Build->resume (
  properties => {
    config_dir => '/Users/tomi/svn/Projects/Text-Textile/_build',
  },
);

$build->dispatch;
