--- #YAML:1.0
name: Text-Textile
version: 0.7
author: ~
abstract: ~
license: unknown
requires:
  perl: 5.6.0
provides:
  Text::Textile:
    file: lib/Text/Textile.pm
    version: 0.7
generated_by: Module::Build version 0.25
