--- #YAML:1.0
name: Text-Textile
version: 0.6
license: unknown
distribution_type: module
requires:
  perl: 5.6.0
recommends: {}
build_requires: {}
conflicts: {}
provides:
  Text::Textile:
    file: lib/Text/Textile.pm
    version: 0.6
generated_by: Module::Build version 0.21
